### ISSUE TITLE
Invalid hostname or IP address on HA discovery

### ISSUE THREAD

**Issue by dcboy87** [pawlizio/my_velux#12]
I'd like to integrate my new Velux KLF200 into Home Assistant, but i'll get following error:

2022-02-09 19:39:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 45, in loop
await self.pulse()
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 62, in pulse
await get_state.do_api_call()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 21, in do_api_call
await self.send_frame()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 33, in send_frame
await self.pyvlx.send_frame(self.request_frame())
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 66, in send_frame
await self.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 43, in connect
await self.connection.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/connection.py", line 87, in connect
self.transport, _ = await self.loop.create_connection(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.178.31', 51200)

2022-02-09 19:39:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 45, in loop
await self.pulse()
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 62, in pulse
await get_state.do_api_call()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 21, in do_api_call
await self.send_frame()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 33, in send_frame
await self.pyvlx.send_frame(self.request_frame())
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 66, in send_frame
await self.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 43, in connect
await self.connection.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/connection.py", line 87, in connect
self.transport, _ = await self.loop.create_connection(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.178.31', 51200)

2022-02-09 19:39:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 45, in loop
await self.pulse()
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 62, in pulse
await get_state.do_api_call()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 21, in do_api_call
await self.send_frame()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 33, in send_frame
await self.pyvlx.send_frame(self.request_frame())
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 66, in send_frame
await self.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 43, in connect
await self.connection.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/connection.py", line 87, in connect
self.transport, _ = await self.loop.create_connection(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
raise exceptions[0]
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
sock = await self._connect_sock(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
await self.sock_connect(sock, address)
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
return await fut
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.178.31', 51200)

2022-02-09 19:39:08 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 45, in loop
await self.pulse()
File "/usr/local/lib/python3.9/site-packages/pyvlx/heartbeat.py", line 62, in pulse
await get_state.do_api_call()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 21, in do_api_call
await self.send_frame()
File "/usr/local/lib/python3.9/site-packages/pyvlx/api/api_event.py", line 33, in send_frame
await self.pyvlx.send_frame(self.request_frame())
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 66, in send_frame
await self.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/pyvlx.py", line 43, in connect
await self.connection.connect()
File "/usr/local/lib/python3.9/site-packages/pyvlx/connection.py", line 87, in connect
self.transport, _ = await self.loop.create_connection(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
transport, protocol = await self._create_connection_transport(
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
await waiter
File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 918, in write
n = self._sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer

I can ping the KLF from my computer and from HA so i don't know where to find my fault... Multiple reboots of HA and KLF didn't help.

**Comment by dcboy87** [comment]
Now i found my mistake:

You have to set your IP address (or hostname) and your password in "" in configuration.yaml

**Comment by pawlizio** [comment]
OK, I think this can be closed then. By the way, did you try configuration via GUI, it is not mandatory with this custom to use the configuration.yaml?
