### ISSUE TITLE
114.0 : NameError: name '_LOGGER' is not defined

### ISSUE THREAD

**Issue by pergolafabio** [pawlizio/my_velux#2]
i see now this issue when updated to 114.0

```

2020-08-12 16:15:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 128, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/my_velux/config_flow.py", line 41, in async_step_zeroconf
    _LOGGER.debug("Received from zeroconf %s", info)
NameError: name '_LOGGER' is not defined
2020-08-12 16:15:47 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 128, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/my_velux/config_flow.py", line 41, in async_step_zeroconf
    _LOGGER.debug("Received from zeroconf %s", info)
NameError: name '_LOGGER' is not defined
```

**Comment by pawlizio** [comment]
Is now fixed

**Comment by pergolafabio** [comment]
Appreciated
