### ISSUE TITLE
Error setting up entry Velux for velux

### ISSUE THREAD

**Issue by neildsb** [pawlizio/my_velux#26]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/velux/__init__.py:36
Integration: Velux
First occurred: 11:18:15 pm (1 occurrences)
Last logged: 11:18:15 pm

Error setting up entry Velux for velux
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/velux/__init__.py", line 36, in async_setup_entry
    await gateway.connect()
  File "/usr/local/lib/python3.11/site-packages/pyvlx/pyvlx.py", line 43, in connect
    await self.klf200.password_enter(password=self.config.password)
  File "/usr/local/lib/python3.11/site-packages/pyvlx/klf200gateway.py", line 127, in password_enter
    raise PyVLXException("Login to KLF 200 failed, check credentials")
pyvlx.exception.PyVLXException: <PyVLXException description="Login to KLF 200 failed, check credentials" />

Home Assistant 2023.7.1
Supervisor 2023.07.1
Operating System 10.3
Frontend 20230705.1 - latest

**Comment by neildsb** [comment]
sorry, just needed to reboot the GW
