### ISSUE TITLE
reboot not initiated on HassOS shutdown host

### ISSUE THREAD

**Issue by pergolafabio** [pawlizio/my_velux#3]
Hey,
since i loaded your custom, never had issues anymore
today i did a shutdown of my HassOS, wanted to make a snapshot
but after start again , seems my_velux was not able to setup

my guess, a reboot of the KLF was not initiated on HassOS shutdown command?

```
2020-08-16 21:08:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component my_velux
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/config/custom_components/my_velux/__init__.py", line 29, in async_setup
    await hass.data[DATA_VELUX].async_start()
  File "/config/custom_components/my_velux/__init__.py", line 72, in async_start
    await self.pyvlx.load_scenes()
  File "/config/custom_components/my_velux/pyvlx/pyvlx.py", line 104, in load_scenes
    await self.scenes.load()
  File "/config/custom_components/my_velux/pyvlx/scenes.py", line 51, in load
    await get_scene_list.do_api_call()
  File "/config/custom_components/my_velux/pyvlx/api_event.py", line 21, in do_api_call
    await self.send_frame()
  File "/config/custom_components/my_velux/pyvlx/api_event.py", line 33, in send_frame
    await self.pyvlx.send_frame(self.request_frame())
  File "/config/custom_components/my_velux/pyvlx/pyvlx.py", line 90, in send_frame
    await self.connect()
  File "/config/custom_components/my_velux/pyvlx/pyvlx.py", line 45, in connect
    await self.connection.connect()
  File "/config/custom_components/my_velux/pyvlx/connection.py", line 91, in connect
    self.transport, _ = await self.loop.create_connection(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
```

**Comment by pawlizio** [comment]
Component completely reworked, I'll close this therefore. Can be reopened if it happens again.
